'use strict';
const { ask } = require('../utils/gemini');

module.exports = {
  name: 'invoice',
  aliases: ['bill', 'receipt', 'generateinvoice'],
  category: 'finance',
  description: 'Generate a professional invoice. Usage: .invoice <details>',
  execute: async (sock, msg, args) => {
    const jid     = msg.key.remoteJid;
    const details = args.join(' ').trim();
    if (!details) {
      return sock.sendMessage(jid, {
        text:
          '🧾 *Invoice Generator*\n━━━━━━━━━━━━━━\n\n' +
          'Usage: *.invoice <details>*\n\n' +
          'Example:\n' +
          '_.invoice Client: John Doe, Services: Web Design, Hours: 10, Rate: $50/hr, Date: May 2026_\n\n' +
          'Or simply:\n' +
          '_.invoice website design for John, 3 pages, $500 total_',
      });
    }
    await sock.sendMessage(jid, { text: '🧾 _Generating invoice..._' });
    try {
      const reply = await ask(
        'Generate a clean professional invoice based on these details: ' + details + '\n\n' +
        'Format it like a real invoice with:\n' +
        '📋 INVOICE #[random 4 digit number]\n' +
        '📅 Date: [today]\n' +
        '👤 Bill To: [client name]\n' +
        '🏢 From: ASTRA-X Services\n\n' +
        '📦 ITEMS:\n[itemized list with quantities and prices]\n\n' +
        '💰 SUBTOTAL: $X\n' +
        '🏛️ TAX (0%): $0\n' +
        '💵 TOTAL DUE: $X\n\n' +
        '📞 Payment Terms: Due within 7 days\n' +
        'Thank you for your business!'
      );
      await sock.sendMessage(jid, {
        text: '🧾 *INVOICE*\n━━━━━━━━━━━━━━\n\n' + reply + '\n\n_Generated by ASTRA-X_',
      }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: '❌ Error: ' + e.message });
    }
  },
};
