'use strict';
const https = require('https');
const { box } = require('../utils/format');

// Free image generation via pollinations.ai (no API key needed)
function generateImage(prompt) {
  return new Promise((resolve, reject) => {
    const encoded = encodeURIComponent('ASTRA-X AI generated image, high quality, detailed: ' + prompt);
    const url = 'https://image.pollinations.ai/prompt/' + encoded + '?width=768&height=768&nologo=true';
    https.get(url, { headers: { 'User-Agent': 'ASTRA-X Bot/4.0' } }, res => {
      if (res.statusCode !== 200) return reject(new Error('Image API returned status ' + res.statusCode));
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

module.exports = {
  name: 'noorphoto',
  aliases: ['nphoto', 'nimage', 'noorimage', 'npic', 'noorpic'],
  category: 'astra-x-ai',
  description: 'Generate AI images for free. Usage: .noorphoto <description>',
  execute: async (sock, msg, args) => {
    const jid    = msg.key.remoteJid;
    const prompt = args.join(' ').trim();

    if (!prompt) return sock.sendMessage(jid, {
      text: box('🖼️ *ASTRA-X PHOTO*',
        '❓ Please describe the image!\n\n📌 *Usage:* .noorphoto <description>\n\n💡 *Examples:*\n.noorphoto sunset over the ocean\n.noorphoto cute cartoon panda eating bamboo\n.noorphoto futuristic city at night with neon lights\n.noorphoto a wolf howling at the moon'
      ),
    });

    await sock.sendMessage(jid, {
      text: '〔 ✧ ᴀsᴛʀᴀ-x ᴛᴇᴄʜ ✧ 〕\n┏━━━━━━━━━━━━━━━━━━━▣\n┃ 🖼️ *ᴀsᴛʀᴀ-x ᴘʜᴏᴛᴏ*\n┠─────────────────────\n┃ _Generating your image..._\n┃ _(This may take ~10 seconds)_\n┗━━━━━━━━━━━━━━━━━━━▣'
    });

    try {
      const imgBuffer = await generateImage(prompt);
      await sock.sendMessage(jid, {
        image: imgBuffer,
        caption: '〔 ✧ ᴀsᴛʀᴀ-x ᴛᴇᴄʜ ✧ 〕\n🖼️ *ASTRA-X PHOTO*\n\n🎨 Prompt: _' + prompt + '_\n\n_Generated by ASTRA-X AI • Free Service_ 🌍',
      }, { quoted: msg });
    } catch (e) {
      await sock.sendMessage(jid, { text: box('🖼️ *ASTRA-X PHOTO*', '❌ Image generation failed: ' + e.message + '\n\nTry a simpler description or try again.') });
    }
  },
};
